server:
  port: 8080

spring:
  application:
    name: consul-producer-app
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: host.docker.internal
        enabled: false
        register: true

        instance-group: demo
        instance-id: ${spring.application.name}:${spring.cloud.client.hostname}
        service-name: ${spring.application.name}

        enableTagOverride: true
        tags: foo=bar, baz

#endpoints:
#  health:
#    sensitive: false
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#
#management:
#  security:
#    enabled: false

logging.level:
  org.springframework.cloud.consul: DEBUG