server:
  port: 8090

external:
  hello: consul-producer-app

spring:
  application:
    name: consul-consumer-app
  cloud:
    consul:
      host: localhost
      port: 8510
      discovery:
        register: false

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

management:
  security:
    enabled: false

logging.level:
  org.springframework.cloud.consul: DEBUG

debug: true