version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Pa55w0rd
    networks:
      - auth-network
  keycloak:
    image: jboss/keycloak:12.0.4
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: Pa55w0rd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
#      JDBC_PARAMS: "ssl=true"
    ports:
      - 8181:8080
    depends_on:
      - postgres
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
